[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "kafka-viz"
version = "0.1.0"
description = "Tool for visualizing Kafka microservices architecture"
requires-python = ">=3.8"
dependencies = [
    "typer>=0.9.0",
    "rich>=13.7.0",
    "regex>=2023.12.25"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "black>=23.0.0",
    "isort>=5.0.0",
    "mypy>=1.0.0"
]

[project.scripts]
kafka-viz = "kafka_viz.cli:app"
